DROP TABLE IF EXISTS "movie";

CREATE TABLE IF NOT EXISTS "movie" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255),
  "director" VARCHAR(255),
  "genre" VARCHAR(255),
  "year" INT 
);

INSERT INTO "movie" ("name", "director", "genre", "year") VALUES 

('8 mile', 'curtis hanson', 'drame', '2002'),
('99 francs', 'jan kounen', 'comedie dramatique', '2007'),
('300', 'zack snyder', 'peplum', '2006'),
('300 - la naissance d''un empire', 'noam murro', 'peplum', '2006'),
('albator', 'shinji aramaki', 'anime japonais', '2006'),
('alice au pays des merveilles', 'tim burton', 'fantastique', '2010'),
('alice de l''autre cote du miroir', 'james bobin', 'fantastique', '2016'),
('arrete-moi si tu peux', 'steven spielberg', 'comedie dramatique', '2002'),
('asterix et le secret de la potion magique', 'alexandre astier', 'animation', '2018'),
('avatar', 'james cameron', 'fantastique', '2009'),
('balto', 'simon wells', 'aninmation', '1995'),
('batman - Le defi', 'tim burton', 'fantastique', '1989'),
('beetlejuice', 'tim burton', 'fantastique', '1988'),
('big eyes', 'tim burton', 'fantastique', '2014'),
('blood diamond', 'edward zwick', 'drame', '2006'),
('brainscan', 'edward furlong', 'horreur', '1994'),
('brice de nice', 'james huth', 'comedie', '2005'),
('casse-tete chinois', 'cedric klapisch', 'Comedie', '2013'),
('charlie et la chocolaterie', 'tim burton', 'fantastique', '2005'),
('constantine', 'francis lawrence', 'fantastique', '2005'),
('cyrano de bergerac', 'jean-paul rappeneau', 'historique', '1990'),
('dark crystal', 'jim henson', 'fantastique', '1982'),
('demoliton man', 'marco brambilla', 'science-fiction', '1993'),
('dikkenek', 'olivier van hoofstadt', 'comedie', '2006'),
('django unchained', 'quentin tarantino', 'western', '2012'),
('dracula untold', 'gary shore', 'fantastique', '2014'),
('e.t l''extra-terrestre', 'steven spielberg', 'science-fiction', '1982'),
('edward aux mains d''argent', 'tim burton', 'fantastique', '1990'),
('fight club', 'david fincher', 'drame', '1999'),
('full metal jacket', 'stanley kubrick', 'drame', '2006'),
('gangs of new york', 'martin scorsese', 'historique', '2002'),
('ghost in the shell', 'rupert sanders', 'drame', '2017'),
('giorgino', 'laurent boutonnat', 'science-fiction', '1999'),
('gremlins', 'joe dante', 'drame', '1999'),
('gremlins 2', 'doe dante', 'drame', '1999'),
('hannibal', 'ridley scott', 'thriller', '2001'),
('hensel et gretel', 'tommy wirkola', 'fantastique', '2013'),
('into the wild', 'sean penn', 'biographie', '2007'),
('jacqou le croquant', 'laurent boutonnat', 'historique', '1999'),
('james et la peche geante', 'disney', 'animation', '1996'),
('judge dredd', 'danny cannon', 'science-fiction', '1995'),
('jumanji', 'joe johnston', 'fantastique', '1995'),
('jurassik park', 'steven spielberg', 'science-fiction', '1993'),
('kirikou et la sorciere', 'michel ocelot', 'animation', '1998'),
('kung fu panda', 'mark osborne', 'animation', '2008'),
('la legende de manolo', 'jorge r. gutierrez', 'animation', '2014'),
('La planete des singes', 'tim burton', 'science-fiction', '2001'),
('lascars', 'albert pereira lazaro', 'animation', '2009'),
('L''auberge espagnole', 'cedric klapisch', 'comedie dramatique', '2002'),
('L''aventure des ewoks - la caravane du courage', 'john korty', 'science-fiction', '1984'),
('le cinquieme element', 'luc besson', 'science-fiction', '1997'),
('le dernier samourai', 'edward zwick', 'historique', '2003'),
('Le fabuleux destin d''amelie poulain', 'joe dante', 'drame', '1999'),
('le labyrinthe de pan', 'guillermo del toro', 'fantastique', '2006'),
('le livre de la jungle', 'jon favreau', 'aventure', '2016'),
('le loup de wallstreet', 'martin scorsese', 'comedie dramatique', '2013'),
('le parfum', 'tom tykwer', 'drame', '2006'),
('le pari', 'didier bourdon', 'comic', '1997'),
('le silence des agneaux', 'jonathan demme', 'thriller', '1991'),
('leon', 'luc besson', 'drame', '1994'),
('les affranchis', 'martin scorsese', 'mafia', '2006'),
('les animaux fantastiques', 'david yates', 'fantastique', '2016'),
('les bronzes', 'patrice leconte', 'comedie', '1978'),
('les choristes', 'christophe barratier', 'comedie dramatique', '2004'),
('les crimes de grindelwald', 'david yates', 'fantastique', '2018'),
('les muppets - ça c''est du cinema', 'james frawley ', 'comedie', '1979'),
('les noces funebres', 'tim burton', 'animation', '2004'),
('les poupees russes', 'cedric klapish', 'comedie dramatique', '2005'),
('les sorcieres de zugarramurdi', 'alex de la iglesia', 'comedie', '2013'),
('les visiteurs', 'jean-marie poire', 'comedie', '1993'),
('les visiteurs 2', 'jean-marie poire', 'comedie', '1998'),
('l''etrange noel de monsieur jack', 'tim burton', 'animation', '1993'),
('l''histoire sans fin', 'wolfgang petersen', 'fantastique', '1984'),
('l''odyssee de pi', 'ang lee', 'drame', '2012'),
('lord of war', 'andrew niccol', 'drame', '2005'),
('mad max - fury road', 'george miller', 'action', '2015'),
('malefique', 'robert stromberg', 'fantasy', '2014'),
('miss peregrine et les enfants particuliers', 'tim burton', 'fantastique', '2016'),
('night call', 'dan gilroy', 'thriller', '2014'),
('orca', 'michael anderson', 'drame', '1977'),
('parasite', 'bong joon ho', 'thriller', '2019'),
('pattaya', 'franck gastambide', 'comedie', '2016'),
('princesse mononoke', 'hayao miyazaki', 'anime japonais', '1997'),
('problemos', 'eric judor', 'comedie', '2017'),
('public ennemies', 'michael mann', 'drame', '2009'),
('pulp fiction', 'quentin tarantino', 'drame', '1994'),
('qui veut la peau de roger rabbit', 'robert zemeckis', 'comedie', '1988'),
('rango', 'gore verbinski', 'animation', '2011'),
('reservoir dogs', 'quentin tarantino', 'drame', '1992'),
('robocop', 'paul verhoeven', 'science-fiction', '1987'),
('saint seyia - asgard', 'takao koyama', 'anime japonais', '1986'),
('seraphine', 'martin provost', 'drame', '2008'),
('serpico', 'sidney lumet', 'drame', '1973'),
('sherlock holmes', 'guy ritchie', 'aventure', '2009'),
('sherlock holmes 2 - jeu d''ombres', 'guy ritchie', 'aventure', '2011'),
('silent hill', 'christophe gans', 'horreur', '2006'),
('silent hill - revelation', 'michael j. bassett', 'horreur', '2012'),
('sin city', 'frank miller', 'film noir', '2005'),
('sin city - j''ai tue pour elle', 'frank miller', 'film noir', '2014'),
('sister act', 'emile ardolino', 'comedie', '1992'),
('sleepy hollow', 'tim burton', 'thriller', '1999'),
('sos fantomes', 'ivan reitman', 'comedie', '1984'),
('south park - le film', 'trey parker', 'animation', '1999'),
('sweeney todd', 'tim burton', 'horreur', '2007'),
('the blues brothers', 'john landis', 'comedie', '1980'),
('the crow', 'alex proyas', 'action', '1994'),
('the mask', 'chuck russell', 'action', '1994'),
('the witch', 'robert eggers', 'horreur', '2015'),
('total recall', 'paul verhoeven', 'science-fiction', '1990'),
('un indien dans la ville', 'herve palud', 'comedie', '1994'),
('v pour vendetta', 'james mcteigue', 'action', '2005'),
('valerian et la cite aux  mille planetes', 'luc besson', 'science-fiction', '2017'),
('vidocq', 'pitof', 'policier', '2001'),
('warcraft - le commencement', 'duncan jones', 'fantasy', '2016'),
('1001 pattes', 'pixar', 'animation', '1998'),
('aladdin', 'disney', 'animation', '1992'),
('bambi', 'disney', 'animation', '1942'),
('blanche-neige et les sept nains', 'disney', 'animation', '1937'),
('dumbo', 'disney', 'animation', '1941'),
('hercule', 'disney', 'animation', '1997'),
('la petite sirene', 'disney', 'animation', '1989'),
('la planete au tresor', 'disney', 'animation', '2002'),
('la princesse et la grenouille', 'disney', 'animation', '2009'),
('le bossu de notre-dame', 'disney', 'animation', '1996'),
('le livre de la jungle', 'disney', 'animation', '1967'),
('le monde de nemo', 'pixar', 'animation', '2003'),
('le roi lion', 'disney', 'animation', '1994'),
('le roi lion 2', 'disney', 'animation', '1998'),
('les mondes de ralph', 'disney', 'animation', '2012'),
('monstres et cie', 'pixar', 'animation', '2001'),
('mulan', 'disney', 'animation', '1998'),
('pocahontas', 'disney', 'animation', '1995'),
('robin des bois', 'disney', 'animation', '1973'),
('rox et rouky', 'disney', 'animation', '1981'),
('tarzan', 'disney', 'animation', '1999'),
('vaiana, la legende du bout du monde', 'disney', 'animation', '1994'),
('harry potter 1 - a l''ecole des sorciers', 'chris columbus', 'fantastique', '2001'),
('harry potter 2 - et la chambre des secrets', 'chris columbus', 'fantastique', '2002'),
('harry potter 3 - et le prisonnier d''azkaban', 'alfonso cuaron', 'fantastique', '2004'),
('harry potter 4 - et la coupe de feu', 'mike newell', 'fantastique', '2005'),
('harry potter 5 - et l''ordre du phenix', 'david yates', 'fantastique', '2007'),
('harry potter 6 - et le prince de sang mele', 'david yates', 'fantastique', '2009'),
('harry potter 7 - et les reliques de la mort - partie 1', 'david yates', 'fantastique', '2010'),
('harry potter 8 - et les reliques de la mort - partie 2', 'david yates', 'fantastique', '2011'),
('la famille addams', 'barry sonnenfeld', 'comedie', '1991'),
('la famille addams - les retrouvailles', 'dave payne', 'comedie', '1998'),
('les valeurs de la famille addams', 'barry sonnenfeld', 'comedie', '1993'),
('le hobbit - un voyage inattendu', 'peter jackson', 'fantasy', '2012'),
('le hobbit - la desolation  de smaug', 'peter jackson', 'fantasy', '2013'),
('le hobbit - la bataille des cinq armees', 'peter jackson', 'fantasy', '2014'),
('le parrain', 'francis ford foppola', 'mafia', '1972'),
('le parrain - partie 2', 'francis ford foppola', 'mafia', '1974'),
('le parrain - partie 3', 'francis ford foppola', 'mafia', '1990'),
('le seigneur des anneaux - la communaute de l''anneau', 'peter jackson', 'fantasy', '2001'),
('le seigneur des anneaux - les deux tours', 'peter jackson', 'fantasy', '2002'),
('le seigneur des anneaux - le retour du roi', 'peter jackson', 'fantasy', '2003'),
('matrix', 'lana wachowski', 'science fiction', '1999'),
('matrix reloaded', 'lana wachowski', 'science fiction', '2003'),
('matrix revolutions', 'lana wachowski', 'science fiction', '2003'),
('men in black', 'barry sonnenfeld', 'science fiction', '1997'),
('men in black 2', 'barry sonnenfeld', 'science fiction', '2002'),
('men in black 3', 'barry sonnenfeld', 'science fiction', '2012'),
('millenium', 'niels arden oplev', 'thriller', '2009'),
('millenium - la fille qui revait d''un bidon d''essence et d''une allumette', 'daniel alfredson', 'thriller', '2009'),
('millenium - la reine dans le palais des courants d''air', 'daniel alfredson', 'thriller', '2009'),
('pirates des caraibes - la maleditcion du black pearl', 'gore verbinski', 'aventure', '2003'),
('pirates des caraibes - le secret du coffre maudit', 'gore verbinski', 'aventure', '2006'),
('pirates des caraibes - jusqu''au bout du monde', 'gore verbinski', 'aventure', '2007'),
('pirates des caraibes - la fontaine de jouvence', 'rob marshall', 'aventure', '2011'),
('pirates des caraibes - la vengeance de salazar', 'joachim Ronning', 'aventure', '2017'),
('rambo', 'ted kotcheff', 'action', '1982'),
('rambo 2 - la mission', 'george pan cosmatos', 'action', '1985'),
('rambo 3', 'peter macdonald', 'action', '1988'),
('rambo 4 - john rambo', 'sylvester stallone ', 'action', '2008'),
('rocky', 'john g. avildsen', 'drame', '1977'),
('rocky 2 - la revanche', 'sylvester stallone', 'drame', '1980'),
('rocky 3 - l''oeil du tigre', 'sylvester stallone', 'drame', '1982'),
('rocky 4', 'sylvester stallone', 'drame', '1986'),
('rocky 5', 'john g. avildsen', 'drame', '1990'),
('rocky balboa', 'sylvester stallone', 'drame', '2007'),
('creed - l''heritage de rocky balboa', 'ryan coogler', 'drame', '2016'),
('spider-man', 'sam raimi', 'science-fiction', '2002'),
('spider-man 2', 'sam raimi', 'science-fiction', '2002'),
('star wars - la menace fantome', 'georges lucas', 'science-fiction', '1999'),
('star wars - l''attaque des clones', 'georges lucas', 'science-fiction', '2002'),
('star wars - la revanche des siths', 'georges lucas', 'science-fiction', '2005'),
('star wars - un nouvel espoir', 'georges lucas', 'science-fiction', '1977'),
('star wars - l''empire contre-attaque', 'georges lucas', 'science-fiction', '1980'),
('star wars - le retour du jedi', 'georges lucas', 'science-fiction', '1983'),
('star wars - le reveil de la force', 'j. j. abrams', 'science-fiction', '2015'),
('star wars - les deniers jedi', 'rian johnson', 'science-fiction', '2017'),
('star wars - l''ascencion de skywalker', 'j. j. abrams', 'science-fiction', '2019'),
('star wars - rogue one', 'rian johnson', 'science-fiction', '2017'),
('star wars - the clone wars', 'dave filoni', 'animation', '2008'),
('x-men', 'bryan singer', 'science-fiction', '2000'),
('x-men 2', 'bryan singer', 'science-fiction', '2003'),
('x-men - l''affrontement final', 'brett ratner', 'science-fiction', '2006'),
('x-men - le commencement', ' matthew vaughn', 'science-fiction', '2011'),
('x-men - days of future past', 'bryan singer', 'science-fiction', '2014'),
('x-men - apocalypse', 'bryan singer', 'science-fiction', '2016'),
('x-men - dark phoenix', 'simon kinberg', 'science-fiction', '2019');